// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Error defines model for Error.
type Error struct {
	// Error code
	Code int32 `json:"code"`

	// Error message
	Message string `json:"message"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// NewProduct defines model for NewProduct.
type NewProduct struct {
	Description *string `json:"Description,omitempty"`
	Name        string  `json:"Name"`
}

// Product defines model for Product.
type Product struct {
	Description *string `json:"Description,omitempty"`
	ID          int     `json:"ID"`
	Name        string  `json:"Name"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Loc  []interface{} `json:"loc"`
	Msg  string        `json:"msg"`
	Type string        `json:"type"`
}

// NewProductJSONBody defines parameters for NewProduct.
type NewProductJSONBody = NewProduct

// UpdateProductJSONBody defines parameters for UpdateProduct.
type UpdateProductJSONBody = NewProduct

// NewProductJSONRequestBody defines body for NewProduct for application/json ContentType.
type NewProductJSONRequestBody = NewProductJSONBody

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = UpdateProductJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Products
	// (GET /products)
	GetProducts(ctx echo.Context) error
	// New Product
	// (POST /products)
	NewProduct(ctx echo.Context) error
	// Delete Product
	// (DELETE /products/{id})
	DeleteProduct(ctx echo.Context, id int) error
	// Get Product
	// (GET /products/{id})
	GetProduct(ctx echo.Context, id int) error
	// Update Product
	// (PUT /products/{id})
	UpdateProduct(ctx echo.Context, id int) error
	// Get Swagger
	// (GET /swagger)
	GetSwagger(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetProducts converts echo context to params.
func (w *ServerInterfaceWrapper) GetProducts(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetProducts(ctx)
	return err
}

// NewProduct converts echo context to params.
func (w *ServerInterfaceWrapper) NewProduct(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.NewProduct(ctx)
	return err
}

// DeleteProduct converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteProduct(ctx, id)
	return err
}

// GetProduct converts echo context to params.
func (w *ServerInterfaceWrapper) GetProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetProduct(ctx, id)
	return err
}

// UpdateProduct converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateProduct(ctx, id)
	return err
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/products", wrapper.GetProducts)
	router.POST(baseURL+"/products", wrapper.NewProduct)
	router.DELETE(baseURL+"/products/:id", wrapper.DeleteProduct)
	router.GET(baseURL+"/products/:id", wrapper.GetProduct)
	router.PUT(baseURL+"/products/:id", wrapper.UpdateProduct)
	router.GET(baseURL+"/swagger", wrapper.GetSwagger)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXQW/bPAz9Kwa/7ygkWbqTbxsybAW2rli7XYoeNItJVdiSJsnrAkP/fZBkx0riNFkb",
	"FD3kFEumyMenR9JpoJCVkgKFNZA3YIo7rGh4/KC11P5BaalQW45hu5AM/S9DU2iuLJcC8michXcE5lJX",
	"1EIOXNizKRCwS4VxiQvU4AhUaAxd7HTUvV4dNVZzsQDnCGj8VXONDPIbaAN25rcELLcldn58pE/X15c/",
	"aMkZ9RF2JMXQUl76J26xClv/a5xDDv+Ne4LGLTvjTX+ujzuLnlbAqdZ0GXB3FkOAVuby5z0W1ju8wIdL",
	"LVld2G24s5SyJondb28xR+CCVpiah/U+hoNRwmsCawD0kRGfz1Lj89mglJ6eVgiQ5PZIYnsVVMpiTT5U",
	"LL/OIb9ptrJqtnK4TdTxWRZ0nY5WQQQqs0jz/LKrRrqNZr0Ysmu/u48Yn0cM1Vom/OxVrXfGxVymsVtS",
	"s3eKA4HfqE0s9MnozWjiwUqFgioOOZyNJiPfLhS1d4HEsYqHw2KBQVee9IDhnEEOH9FedjY+EaOkMPFG",
	"ppNJ7FfCoghHqVIlj/SO701UYizpgyu/k0hyY9/aoFkCZKP4Hdnocld1UaAx87rMuuPe5dvp9J8gP4Z0",
	"qM0MIOlNslUvYzindWmPBmVn8FrgH4WFRZZha0PA1FVF9TJebk+qI6CkGZDAWkfyUkZj30u2PBr8JIBb",
	"Lxera3TPlN1Bajsp6GkKusCHrCeR9A1l3HDm4uQv0eK2qmZhvxeWoppWaFGb0NS5D+77FBAQYQABZ7Cp",
	"DZKk17WLYLY5Adzt81R0EsgTBRKvOUva+p4x8+qlcGooLzSSwkSqB8TyXTH60q3jNPVOIl2JNApwffCZ",
	"B7rwennkQ/qqNXnm1R7wXZz+Xzjogl9T+Xc0Oefc3wAAAP//8+sNhT8RAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
