resources:
  repositories:
  - repository: ag-apim-aks-simplified-repo
    type: github
    endpoint: cbellee
    name: cbellee/azure-iac-examples
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ./bicep/ag-apim-aks-simplified/*
pool:
  vmImage: 'ubuntu-latest'
  poolName: 'Azure Pipelines'

variables:
  - name: azureConnection
    value: 'internal_azure_subscription'
  - name: vmImage
    value: 'ubuntu-latest'
  - name: poolName
    value: 'Azure Pipelines'

stages:
  - template: build-api.yaml
    parameters:
      vmImage: $(vmImage)
      poolName: $(poolName)
      environment: dev
      azureConnection: $(azureConnection)
      resourceGroupName: $(environment)-appgwy-apim-aks-rg
      apiImageName: order-api:v0.1.0
      apiName: order-api
      apiPort: '8080'
     