parameters:
  - name: 'vmImage'
    default: 'ubuntu-latest'
    type: string
  - name: 'poolName'
    default: 'Azure Pipelines'
  - name: 'location'
    default: 'australiaeast'
    type: string
  - name: 'environment'
    type: string
  - name: 'azureConnection'
    default: 'internal_azure_subscription'
    type: string
  - name: subscriptionId
    default: 'b2375b5f-8dab-4436-b87c-32bc7fdce5d0'
    type: string
  - name: 'resourceGroupName'
    default: 'ag-apim-aks-rg'
    type: string
  - name:  'aksAdminGroupObjectId'
    default: 'f6a900e2-df11-43e7-ba3e-22be99d3cede'
    type: string
  - name: 'publicDnsZone'
    type: string
  - name: 'publicDnsZoneResourceGroup'
    type: string
  - name: 'reactSpaSvcIp'
    type: string
  - name: 'keyVaultName'
    type: string
  - name: 'tlsCertSecretId'
    type: string
  - name: 'keyVaultResourceGroupName'
    type: string
  - name: gitRepoUrl
    type: string
stages:
- stage: ag_apim_aks_simplified_${{parameters.environment}}
  jobs:
  - deployment: 
    displayName: 'infrastructure_deployment'
    pool:
      name: ${{parameters.poolName}}
    environment: ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'drop'
                targetPath: $(System.ArtifactsDirectory)
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Validate Infrastructure Templates'
              inputs:
                azureResourceManagerConnection: ${{parameters.azureConnection}}
                subscriptionId: ${{parameters.subscriptionId}}
                resourceGroupName: ${{parameters.environment}}-${{parameters.resourceGroupName}}
                location: ${{parameters.location}}
                csmFile: '$(System.ArtifactsDirectory)/main.bicep'
                csmParametersFile: $(System.ArtifactsDirectory)/${{parameters.environment}}.parameters.json
                overrideParameters: '-publicDnsZoneName ${{parameters.publicDnsZone}} -publicDnsZoneResourceGroup ${{parameters.publicDnsZoneResourceGroup}} -privateDnsZoneName "${{parameters.environment}}.${{parameters.publicDnsZone}}" -aksAdminGroupObjectId ${{parameters.aksAdminGroupObjectId}} -kubernetesSpaIpAddress ${{parameters.reactSpaSvcIp}} -keyVaultName ${{parameters.keyVaultName}} -tlsCertSecretId ${{parameters.tlsCertSecretId}} -location ${{parameters.location}} -keyVaultResourceGroupName ${{parameters.keyVaultResourceGroupName}} -gitRepoUrl ${{parameters.gitRepoUrl}}'
                deploymentMode: Validation
                deploymentName: '${{parameters.environment}}-validate-infra-deployment'
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Deploy Infrastructure Templates'
              inputs:
                azureResourceManagerConnection: ${{parameters.azureConnection}}
                subscriptionId: ${{parameters.subscriptionId}}
                resourceGroupName: ${{parameters.environment}}-${{parameters.resourceGroupName}}
                location: ${{parameters.location}}
                csmFile: '$(System.ArtifactsDirectory)/main.bicep'
                csmParametersFile: $(System.ArtifactsDirectory)/${{parameters.environment}}.parameters.json
                overrideParameters: '-publicDnsZoneName ${{parameters.publicDnsZone}} -publicDnsZoneResourceGroup ${{parameters.publicDnsZoneResourceGroup}} -privateDnsZoneName "${{parameters.environment}}.${{parameters.publicDnsZone}}" -aksAdminGroupObjectId ${{parameters.aksAdminGroupObjectId}} -kubernetesSpaIpAddress ${{parameters.reactSpaSvcIp}} -keyVaultName ${{parameters.keyVaultName}} -tlsCertSecretId ${{parameters.tlsCertSecretId}} -location ${{parameters.location}} -keyVaultResourceGroupName ${{parameters.keyVaultResourceGroupName}}'
                deploymentMode: Incremental
                deploymentName: '${{parameters.environment}}-infra-deployment'