apiVersion: v1
kind: Service
metadata:
  namespace: apis
  name: product-svc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "aksLoadBalancerSubnet"
spec:
  type: LoadBalancer
  loadBalancerIP: "{{SVC_IP_ADDRESS}}"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: product-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apis
  name: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: product-api
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "64Mi"
          requests:
            cpu: "250m"
            memory: "32Mi"
        image: "{{IMAGE_TAG}}"
        ports:
        - containerPort: 8081
          name: http
      